export const USER_INTERFACE_ID="user-interface"
export const SEARCH_BUTTON_ID="search-button"
export const SEARCH_INPUT_ID="search-input"
export const SIGN_UP_BUTTON_ID="sign-up-button"
export const SIGN_UP_FORM_ID="sign-up-form"
export const SIGN_IN_BUTTON_ID="sign-in-button"
export const SIGN_IN_FORM_ID="sign-in-form-id"
